---
language: python
services: docker

env:
  global:
    - ROLE_NAME: awx
  matrix:
    - MOLECULE_DISTRO: centos7

script:
  # Run tests (increasing the travis_wait timeout).
  - echo "hello world"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
